// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: message.proto at 38:1
package com.dronja.testprotobufwire;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class csmpMsgDh1Proto extends Message<csmpMsgDh1Proto, csmpMsgDh1Proto.Builder> {
  public static final ProtoAdapter<csmpMsgDh1Proto> ADAPTER = new ProtoAdapter_csmpMsgDh1Proto();

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_PKRMSGDH1PROTO = ByteString.EMPTY;

  public static final ByteString DEFAULT_HCSMSGDH1PROTO = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString pkrMsgDh1Proto;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString hcsMsgDh1Proto;

  public csmpMsgDh1Proto(ByteString pkrMsgDh1Proto, ByteString hcsMsgDh1Proto) {
    this(pkrMsgDh1Proto, hcsMsgDh1Proto, ByteString.EMPTY);
  }

  public csmpMsgDh1Proto(ByteString pkrMsgDh1Proto, ByteString hcsMsgDh1Proto, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.pkrMsgDh1Proto = pkrMsgDh1Proto;
    this.hcsMsgDh1Proto = hcsMsgDh1Proto;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.pkrMsgDh1Proto = pkrMsgDh1Proto;
    builder.hcsMsgDh1Proto = hcsMsgDh1Proto;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof csmpMsgDh1Proto)) return false;
    csmpMsgDh1Proto o = (csmpMsgDh1Proto) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(pkrMsgDh1Proto, o.pkrMsgDh1Proto)
        && Internal.equals(hcsMsgDh1Proto, o.hcsMsgDh1Proto);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (pkrMsgDh1Proto != null ? pkrMsgDh1Proto.hashCode() : 0);
      result = result * 37 + (hcsMsgDh1Proto != null ? hcsMsgDh1Proto.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (pkrMsgDh1Proto != null) builder.append(", pkrMsgDh1Proto=").append(pkrMsgDh1Proto);
    if (hcsMsgDh1Proto != null) builder.append(", hcsMsgDh1Proto=").append(hcsMsgDh1Proto);
    return builder.replace(0, 2, "csmpMsgDh1Proto{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<csmpMsgDh1Proto, Builder> {
    public ByteString pkrMsgDh1Proto;

    public ByteString hcsMsgDh1Proto;

    public Builder() {
    }

    public Builder pkrMsgDh1Proto(ByteString pkrMsgDh1Proto) {
      this.pkrMsgDh1Proto = pkrMsgDh1Proto;
      return this;
    }

    public Builder hcsMsgDh1Proto(ByteString hcsMsgDh1Proto) {
      this.hcsMsgDh1Proto = hcsMsgDh1Proto;
      return this;
    }

    @Override
    public csmpMsgDh1Proto build() {
      return new csmpMsgDh1Proto(pkrMsgDh1Proto, hcsMsgDh1Proto, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_csmpMsgDh1Proto extends ProtoAdapter<csmpMsgDh1Proto> {
    ProtoAdapter_csmpMsgDh1Proto() {
      super(FieldEncoding.LENGTH_DELIMITED, csmpMsgDh1Proto.class);
    }

    @Override
    public int encodedSize(csmpMsgDh1Proto value) {
      return (value.pkrMsgDh1Proto != null ? ProtoAdapter.BYTES.encodedSizeWithTag(1, value.pkrMsgDh1Proto) : 0)
          + (value.hcsMsgDh1Proto != null ? ProtoAdapter.BYTES.encodedSizeWithTag(2, value.hcsMsgDh1Proto) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, csmpMsgDh1Proto value) throws IOException {
      if (value.pkrMsgDh1Proto != null) ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.pkrMsgDh1Proto);
      if (value.hcsMsgDh1Proto != null) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.hcsMsgDh1Proto);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public csmpMsgDh1Proto decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.pkrMsgDh1Proto(ProtoAdapter.BYTES.decode(reader)); break;
          case 2: builder.hcsMsgDh1Proto(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public csmpMsgDh1Proto redact(csmpMsgDh1Proto value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
