// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: message.proto at 43:1
package com.dronja.testprotobufwire;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class csmpMsgDh2Proto extends Message<csmpMsgDh2Proto, csmpMsgDh2Proto.Builder> {
  public static final ProtoAdapter<csmpMsgDh2Proto> ADAPTER = new ProtoAdapter_csmpMsgDh2Proto();

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_PKIMSGDH2PROTO = ByteString.EMPTY;

  public static final ByteString DEFAULT_MACIMSGDH2PROTO = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString pkiMsgDh2Proto;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString maciMsgDh2Proto;

  public csmpMsgDh2Proto(ByteString pkiMsgDh2Proto, ByteString maciMsgDh2Proto) {
    this(pkiMsgDh2Proto, maciMsgDh2Proto, ByteString.EMPTY);
  }

  public csmpMsgDh2Proto(ByteString pkiMsgDh2Proto, ByteString maciMsgDh2Proto, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.pkiMsgDh2Proto = pkiMsgDh2Proto;
    this.maciMsgDh2Proto = maciMsgDh2Proto;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.pkiMsgDh2Proto = pkiMsgDh2Proto;
    builder.maciMsgDh2Proto = maciMsgDh2Proto;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof csmpMsgDh2Proto)) return false;
    csmpMsgDh2Proto o = (csmpMsgDh2Proto) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(pkiMsgDh2Proto, o.pkiMsgDh2Proto)
        && Internal.equals(maciMsgDh2Proto, o.maciMsgDh2Proto);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (pkiMsgDh2Proto != null ? pkiMsgDh2Proto.hashCode() : 0);
      result = result * 37 + (maciMsgDh2Proto != null ? maciMsgDh2Proto.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (pkiMsgDh2Proto != null) builder.append(", pkiMsgDh2Proto=").append(pkiMsgDh2Proto);
    if (maciMsgDh2Proto != null) builder.append(", maciMsgDh2Proto=").append(maciMsgDh2Proto);
    return builder.replace(0, 2, "csmpMsgDh2Proto{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<csmpMsgDh2Proto, Builder> {
    public ByteString pkiMsgDh2Proto;

    public ByteString maciMsgDh2Proto;

    public Builder() {
    }

    public Builder pkiMsgDh2Proto(ByteString pkiMsgDh2Proto) {
      this.pkiMsgDh2Proto = pkiMsgDh2Proto;
      return this;
    }

    public Builder maciMsgDh2Proto(ByteString maciMsgDh2Proto) {
      this.maciMsgDh2Proto = maciMsgDh2Proto;
      return this;
    }

    @Override
    public csmpMsgDh2Proto build() {
      return new csmpMsgDh2Proto(pkiMsgDh2Proto, maciMsgDh2Proto, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_csmpMsgDh2Proto extends ProtoAdapter<csmpMsgDh2Proto> {
    ProtoAdapter_csmpMsgDh2Proto() {
      super(FieldEncoding.LENGTH_DELIMITED, csmpMsgDh2Proto.class);
    }

    @Override
    public int encodedSize(csmpMsgDh2Proto value) {
      return (value.pkiMsgDh2Proto != null ? ProtoAdapter.BYTES.encodedSizeWithTag(1, value.pkiMsgDh2Proto) : 0)
          + (value.maciMsgDh2Proto != null ? ProtoAdapter.BYTES.encodedSizeWithTag(2, value.maciMsgDh2Proto) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, csmpMsgDh2Proto value) throws IOException {
      if (value.pkiMsgDh2Proto != null) ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.pkiMsgDh2Proto);
      if (value.maciMsgDh2Proto != null) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.maciMsgDh2Proto);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public csmpMsgDh2Proto decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.pkiMsgDh2Proto(ProtoAdapter.BYTES.decode(reader)); break;
          case 2: builder.maciMsgDh2Proto(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public csmpMsgDh2Proto redact(csmpMsgDh2Proto value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
