// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: message.proto at 48:1
package com.dronja.testprotobufwire;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class csmpMsgConfirmProto extends Message<csmpMsgConfirmProto, csmpMsgConfirmProto.Builder> {
  public static final ProtoAdapter<csmpMsgConfirmProto> ADAPTER = new ProtoAdapter_csmpMsgConfirmProto();

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_MACRMSGCONFIRMPROTO = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString macrMsgConfirmProto;

  public csmpMsgConfirmProto(ByteString macrMsgConfirmProto) {
    this(macrMsgConfirmProto, ByteString.EMPTY);
  }

  public csmpMsgConfirmProto(ByteString macrMsgConfirmProto, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.macrMsgConfirmProto = macrMsgConfirmProto;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.macrMsgConfirmProto = macrMsgConfirmProto;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof csmpMsgConfirmProto)) return false;
    csmpMsgConfirmProto o = (csmpMsgConfirmProto) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(macrMsgConfirmProto, o.macrMsgConfirmProto);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (macrMsgConfirmProto != null ? macrMsgConfirmProto.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (macrMsgConfirmProto != null) builder.append(", macrMsgConfirmProto=").append(macrMsgConfirmProto);
    return builder.replace(0, 2, "csmpMsgConfirmProto{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<csmpMsgConfirmProto, Builder> {
    public ByteString macrMsgConfirmProto;

    public Builder() {
    }

    public Builder macrMsgConfirmProto(ByteString macrMsgConfirmProto) {
      this.macrMsgConfirmProto = macrMsgConfirmProto;
      return this;
    }

    @Override
    public csmpMsgConfirmProto build() {
      return new csmpMsgConfirmProto(macrMsgConfirmProto, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_csmpMsgConfirmProto extends ProtoAdapter<csmpMsgConfirmProto> {
    ProtoAdapter_csmpMsgConfirmProto() {
      super(FieldEncoding.LENGTH_DELIMITED, csmpMsgConfirmProto.class);
    }

    @Override
    public int encodedSize(csmpMsgConfirmProto value) {
      return (value.macrMsgConfirmProto != null ? ProtoAdapter.BYTES.encodedSizeWithTag(1, value.macrMsgConfirmProto) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, csmpMsgConfirmProto value) throws IOException {
      if (value.macrMsgConfirmProto != null) ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.macrMsgConfirmProto);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public csmpMsgConfirmProto decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.macrMsgConfirmProto(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public csmpMsgConfirmProto redact(csmpMsgConfirmProto value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
