// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: message.proto at 15:1
package com.dronja.testprotobufwire;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * [END csharp_declaration]
 */
public final class GenericMessage extends Message<GenericMessage, GenericMessage.Builder> {
  public static final ProtoAdapter<GenericMessage> ADAPTER = new ProtoAdapter_GenericMessage();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_MESSAGE_ID = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String message_id;

  @WireField(
      tag = 2,
      adapter = "com.dronja.testprotobufwire.csmpMsgCommitProto#ADAPTER"
  )
  public final csmpMsgCommitProto commitProto;

  @WireField(
      tag = 3,
      adapter = "com.dronja.testprotobufwire.csmpMsgDh1Proto#ADAPTER"
  )
  public final csmpMsgDh1Proto msgDH1Proto;

  @WireField(
      tag = 4,
      adapter = "com.dronja.testprotobufwire.csmpMsgDh2Proto#ADAPTER"
  )
  public final csmpMsgDh2Proto msgDH2Proto;

  @WireField(
      tag = 5,
      adapter = "com.dronja.testprotobufwire.csmpMsgConfirmProto#ADAPTER"
  )
  public final csmpMsgConfirmProto macrProto;

  @WireField(
      tag = 6,
      adapter = "com.dronja.testprotobufwire.csmpMsgEncrProto#ADAPTER"
  )
  public final csmpMsgEncrProto encrProto;

  public GenericMessage(String message_id, csmpMsgCommitProto commitProto, csmpMsgDh1Proto msgDH1Proto, csmpMsgDh2Proto msgDH2Proto, csmpMsgConfirmProto macrProto, csmpMsgEncrProto encrProto) {
    this(message_id, commitProto, msgDH1Proto, msgDH2Proto, macrProto, encrProto, ByteString.EMPTY);
  }

  public GenericMessage(String message_id, csmpMsgCommitProto commitProto, csmpMsgDh1Proto msgDH1Proto, csmpMsgDh2Proto msgDH2Proto, csmpMsgConfirmProto macrProto, csmpMsgEncrProto encrProto, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (Internal.countNonNull(commitProto, msgDH1Proto, msgDH2Proto, macrProto, encrProto) > 1) {
      throw new IllegalArgumentException("at most one of commitProto, msgDH1Proto, msgDH2Proto, macrProto, encrProto may be non-null");
    }
    this.message_id = message_id;
    this.commitProto = commitProto;
    this.msgDH1Proto = msgDH1Proto;
    this.msgDH2Proto = msgDH2Proto;
    this.macrProto = macrProto;
    this.encrProto = encrProto;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.message_id = message_id;
    builder.commitProto = commitProto;
    builder.msgDH1Proto = msgDH1Proto;
    builder.msgDH2Proto = msgDH2Proto;
    builder.macrProto = macrProto;
    builder.encrProto = encrProto;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GenericMessage)) return false;
    GenericMessage o = (GenericMessage) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(message_id, o.message_id)
        && Internal.equals(commitProto, o.commitProto)
        && Internal.equals(msgDH1Proto, o.msgDH1Proto)
        && Internal.equals(msgDH2Proto, o.msgDH2Proto)
        && Internal.equals(macrProto, o.macrProto)
        && Internal.equals(encrProto, o.encrProto);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (message_id != null ? message_id.hashCode() : 0);
      result = result * 37 + (commitProto != null ? commitProto.hashCode() : 0);
      result = result * 37 + (msgDH1Proto != null ? msgDH1Proto.hashCode() : 0);
      result = result * 37 + (msgDH2Proto != null ? msgDH2Proto.hashCode() : 0);
      result = result * 37 + (macrProto != null ? macrProto.hashCode() : 0);
      result = result * 37 + (encrProto != null ? encrProto.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (message_id != null) builder.append(", message_id=").append(message_id);
    if (commitProto != null) builder.append(", commitProto=").append(commitProto);
    if (msgDH1Proto != null) builder.append(", msgDH1Proto=").append(msgDH1Proto);
    if (msgDH2Proto != null) builder.append(", msgDH2Proto=").append(msgDH2Proto);
    if (macrProto != null) builder.append(", macrProto=").append(macrProto);
    if (encrProto != null) builder.append(", encrProto=").append(encrProto);
    return builder.replace(0, 2, "GenericMessage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GenericMessage, Builder> {
    public String message_id;

    public csmpMsgCommitProto commitProto;

    public csmpMsgDh1Proto msgDH1Proto;

    public csmpMsgDh2Proto msgDH2Proto;

    public csmpMsgConfirmProto macrProto;

    public csmpMsgEncrProto encrProto;

    public Builder() {
    }

    public Builder message_id(String message_id) {
      this.message_id = message_id;
      return this;
    }

    public Builder commitProto(csmpMsgCommitProto commitProto) {
      this.commitProto = commitProto;
      this.msgDH1Proto = null;
      this.msgDH2Proto = null;
      this.macrProto = null;
      this.encrProto = null;
      return this;
    }

    public Builder msgDH1Proto(csmpMsgDh1Proto msgDH1Proto) {
      this.msgDH1Proto = msgDH1Proto;
      this.commitProto = null;
      this.msgDH2Proto = null;
      this.macrProto = null;
      this.encrProto = null;
      return this;
    }

    public Builder msgDH2Proto(csmpMsgDh2Proto msgDH2Proto) {
      this.msgDH2Proto = msgDH2Proto;
      this.commitProto = null;
      this.msgDH1Proto = null;
      this.macrProto = null;
      this.encrProto = null;
      return this;
    }

    public Builder macrProto(csmpMsgConfirmProto macrProto) {
      this.macrProto = macrProto;
      this.commitProto = null;
      this.msgDH1Proto = null;
      this.msgDH2Proto = null;
      this.encrProto = null;
      return this;
    }

    public Builder encrProto(csmpMsgEncrProto encrProto) {
      this.encrProto = encrProto;
      this.commitProto = null;
      this.msgDH1Proto = null;
      this.msgDH2Proto = null;
      this.macrProto = null;
      return this;
    }

    @Override
    public GenericMessage build() {
      return new GenericMessage(message_id, commitProto, msgDH1Proto, msgDH2Proto, macrProto, encrProto, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GenericMessage extends ProtoAdapter<GenericMessage> {
    ProtoAdapter_GenericMessage() {
      super(FieldEncoding.LENGTH_DELIMITED, GenericMessage.class);
    }

    @Override
    public int encodedSize(GenericMessage value) {
      return (value.message_id != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.message_id) : 0)
          + (value.commitProto != null ? csmpMsgCommitProto.ADAPTER.encodedSizeWithTag(2, value.commitProto) : 0)
          + (value.msgDH1Proto != null ? csmpMsgDh1Proto.ADAPTER.encodedSizeWithTag(3, value.msgDH1Proto) : 0)
          + (value.msgDH2Proto != null ? csmpMsgDh2Proto.ADAPTER.encodedSizeWithTag(4, value.msgDH2Proto) : 0)
          + (value.macrProto != null ? csmpMsgConfirmProto.ADAPTER.encodedSizeWithTag(5, value.macrProto) : 0)
          + (value.encrProto != null ? csmpMsgEncrProto.ADAPTER.encodedSizeWithTag(6, value.encrProto) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GenericMessage value) throws IOException {
      if (value.message_id != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.message_id);
      if (value.commitProto != null) csmpMsgCommitProto.ADAPTER.encodeWithTag(writer, 2, value.commitProto);
      if (value.msgDH1Proto != null) csmpMsgDh1Proto.ADAPTER.encodeWithTag(writer, 3, value.msgDH1Proto);
      if (value.msgDH2Proto != null) csmpMsgDh2Proto.ADAPTER.encodeWithTag(writer, 4, value.msgDH2Proto);
      if (value.macrProto != null) csmpMsgConfirmProto.ADAPTER.encodeWithTag(writer, 5, value.macrProto);
      if (value.encrProto != null) csmpMsgEncrProto.ADAPTER.encodeWithTag(writer, 6, value.encrProto);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GenericMessage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.message_id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.commitProto(csmpMsgCommitProto.ADAPTER.decode(reader)); break;
          case 3: builder.msgDH1Proto(csmpMsgDh1Proto.ADAPTER.decode(reader)); break;
          case 4: builder.msgDH2Proto(csmpMsgDh2Proto.ADAPTER.decode(reader)); break;
          case 5: builder.macrProto(csmpMsgConfirmProto.ADAPTER.decode(reader)); break;
          case 6: builder.encrProto(csmpMsgEncrProto.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GenericMessage redact(GenericMessage value) {
      Builder builder = value.newBuilder();
      if (builder.commitProto != null) builder.commitProto = csmpMsgCommitProto.ADAPTER.redact(builder.commitProto);
      if (builder.msgDH1Proto != null) builder.msgDH1Proto = csmpMsgDh1Proto.ADAPTER.redact(builder.msgDH1Proto);
      if (builder.msgDH2Proto != null) builder.msgDH2Proto = csmpMsgDh2Proto.ADAPTER.redact(builder.msgDH2Proto);
      if (builder.macrProto != null) builder.macrProto = csmpMsgConfirmProto.ADAPTER.redact(builder.macrProto);
      if (builder.encrProto != null) builder.encrProto = csmpMsgEncrProto.ADAPTER.redact(builder.encrProto);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
